#!/bin/sh
#
# Copyright (c) 2023 ydalton
#
# readhdr: A nice little wrapper for less (or what pager have you) used for 
# reading C header files.

INVOKED_NAME=$0

# set defaults if these variables aren't set
[ -z $PAGER ] && PAGER=/usr/bin/less
[ -z $INCLUDE_DIR ] && INCLUDE_DIR=/usr/include

usage() {
	echo "usage: $(basename $INVOKED_NAME) FILE [PATTERN]"
	echo "Read FILE and located in $INCLUDE_DIR."
	echo "If PATTERN is specified, search in FILE for PATTERN."
	exit 1
}

ARGC=$#
[ $ARGC -lt 1 ] && usage
[ "$1" = "--help" ] && usage

FILE_NAME=$1

[ $ARGC -gt 2 ] && usage

PATTERN=$2

if [ ! -z $PATTERN ]; then
	# FIXME: this line is specific to less, make this more general to
	# different pagers
	PAGER="$PAGER -p $PATTERN"
fi

exec $PAGER $INCLUDE_DIR/$FILE_NAME

exit 0
